/* ============================================================================
 * RENAMED DECOMPILED C CODE - Second Pass
 * 
 * This file has been processed to rename variables, functions, and constants
 * to more readable names based on:
 * 1. C_CODE_PORTING_TRACKER.md documentation
 * 2. Decompiler function comments
 * 3. Code patterns and context
 *
 * Renames applied:
 * Pass 1 (First Pass):
 * - FUN_ functions renamed based on behavior:
 *   - FUN_100019f0 -> grim_config_save
 *   - FUN_10001a30 -> grim_config_load
 *   - FUN_10001e90 -> grim_dialog_populate_resolutions
 *   - FUN_10002cf0 -> grim_device_reset
 *   - FUN_10002f60 -> grim_bitmap_delete
 *   - FUN_10002f80 -> grim_timer_update
 *   - FUN_10002fc0 -> grim_state_init
 *   - FUN_10003090 -> grim_timer_tick
 *   - FUN_100030b0 -> grim_device_test_and_reset
 *   - FUN_10003c00 -> grim_main_loop
 *   - FUN_10004280 -> grim_d3d_shutdown
 *   - FUN_10004350 -> grim_vertex_buffer_create
 *   - FUN_100044e0 -> grim_vertex_buffer_release
 *   - FUN_10004520 -> grim_d3d_render_states_init
 *   - FUN_10004920 -> grim_input_init
 *   - FUN_10004970 -> grim_input_update
 * - DAT_ globals renamed based on usage:
 *   - Window handles: grim_window_handle, grim_dialog_handle, etc.
 *   - D3D state: grim_device_cooperative, grim_device_lost_flag, etc.
 *   - Display: grim_display_width, grim_display_bit_depth, etc.
 *   - Input: grim_keyboard_enabled_flag, grim_frame_delta_time, etc.
 *   - Render state: grim_alpha_blend_enabled, grim_src/dest_blend_mode
 *   - Rotation matrix: grim_rotation_m00/m01/m10/m11, grim_rotation_sin
 *   - UV coordinates: grim_uv_u2/v2/u3/v3 (completes existing u0/v0/u1/v1)
 *   - Viewport: grim_viewport_left/top/right/bottom
 *   - Present params: grim_present_format/refresh_rate/windowed/etc.
 * - String constants named descriptively
 *
 * Original file: grim.dll_decompiled.c
 * Pass 2 (Second Pass):
 * - Input system: grim_joystick_button_down/shutdown, grim_keyboard_shutdown
 * - Mouse: grim_mouse_init/shutdown/set_position/button_pressed
 * - Texture format: grim_format_info_init/lookup/compare/find_best/find_supported
 * - Image loading: grim_image_load_from_memory/file_ex, grim_image_get_info
 * - PNG: grim_png_read_state_machine/header/data/rows/chunk
 * - Texture: grim_texture_create_empty/lock_surface/unlock_surface/fill_rect/blit
 * - Audio: grim_sound_init/shutdown/play/stop/load_wav/unload
 * - Music: grim_music_init/shutdown/play/stop/set_volume
 * - Font: grim_font_create/destroy/draw_text/measure_text
 * - File/memory: grim_file_stream_*, grim_alloc_context_*, grim_zip_*
 * - ~100 string constants renamed to descriptive names
 *
 * Generated by: Second pass rename
 * ============================================================================ */
/* Decompiled from: grim.dll */
